# Generated by Django 3.0 on 2020-02-15 15:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            managers=[
                ('students1', django.db.models.manager.Manager()),
            ],
        ),
    ]
