# Generated by Django 3.0 on 2020-02-15 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='borthday',
            field=models.DateTimeField(default=datetime.date(1990, 10, 12)),
        ),
        migrations.AlterModelTable(
            name='student',
            table='custom_table',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField(default=False)),
                ('hstsdfu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='apps.Student')),
            ],
        ),
    ]
