# Generated by Django 3.0 on 2020-02-15 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200215_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='borthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
