# Generated by Django 3.0 on 2020-02-15 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200215_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='borthday',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 23, 56, 54, 346609)),
        ),
    ]
